token: ${TOKEN}
description: "This bot automatically repost x.com and twitter.com posts as fxtwitter ones."
version: "1.1.1"
color: 0x1d9bf0
locale: "en"
guild: ${DEV_GUILD}
hot_reload: ${HOT_RELOAD}

fx_domain: "https://fxtwitter.com"

log:
  file: "log.txt"
  stream_to_err: false
  channel: ${LOG_CHANNEL}
  date_format: "%d/%m/%Y %H:%M:%S"
  format: "[{asctime}] {levelformat} {name:<20} {message}"

invite_link: "https://discord.com/api/oauth2/authorize?client_id=1164651057243238400&permissions=274877934592&scope=bot%20applications.commands"
